### ISSUE TITLE
Muse Proto cannot be used as a Bluetooth Proxy for HA

### ISSUE THREAD

**Issue by DigitalFeonix** [esphome/media-players#19]
I updated my ESPHome installation to 2022.8.3.

I added the required lines to be a bluetooth proxy into the config:

```
substitutions:
  name: raspiaudio-muse-proto-d3ffd0
packages:
  raspiaudio.muse-proto: github://esphome/media-players/raspiaudio-muse-proto.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32_ble_tracker:
bluetooth_proxy:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

After compiling the installation fails, stating the image is too big for the Muse Proto

```
Processing raspiaudio-muse-proto-d3ffd0 (board: esp-wrover-kit; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 1.0
|-- FS @ 1.0
|-- Update @ 1.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 1.1.0
|-- ESPmDNS @ 1.0
|-- Improv @ 1.2.1
|-- WiFiClientSecure @ 1.0
|-- HTTPClient @ 1.2
|-- ESP32-audioI2S @ 2.1.0
|-- FastLED @ 3.3.2
RAM:   [==        ]  17.2% (used 56392 bytes from 327680 bytes)
Error: The program size (1899116 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
Flash: [==========]  103.5% (used 1899116 bytes from 1835008 bytes)
========================= [FAILED] Took 10.44 seconds =========================
```

Is there any options to be able to still use as a ESPHome media player AND a bluetooth proxy?
