### ISSUE TITLE
L/R channels backwards on M5Stack Atom Speaker Kit

### ISSUE THREAD

**Issue by wryandginger** [esphome/media-players#22]
Using the 3.5mm headphone jack on the M5Stack Atom Speaker Kit puts the mono audio on the wrong channel.
This creates a ground short in most cheap speakers and produces terrible sound output unless you have your jack half-plugged in.

Problems disappear when swapping channels. I did this by cutting and rewriting a 3.5mm aux cable or using two RCA to 3.5mm adapters and putting red to white and white to red, but that's kind of a fiddly mess.

Would it be possible to either change the YAML for the speaker kit's DAC to stereo or correct the sound output?

**Comment by wryandginger** [comment]
Just tested this YAML for the M5Stack Atom Speaker Kit. This seems to solve the problem:
```
substitutions:
  name: "m5stack-atom-speaker-kit-XXXXXX"
  friendly_name: "Friendly Name"
  wifi_ap_password: ""

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  project:
    name: m5stack.atom-speaker-kit
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

improv_serial:

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_lrclk_pin: GPIO21
    i2s_dout_pin: GPIO25
    i2s_bclk_pin: GPIO22
    mode: stereo

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${friendly_name} Button
    on_click:
      - media_player.toggle: media_out

light:
  - platform: fastled_clockless
    name: ${friendly_name}
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
```
