### ISSUE TITLE
Scrambled Pico TTS output when played on the device

### ISSUE THREAD

**Issue by alfwro13** [esphome/media-players#9]
Hi,
I have flushed my M5Stack Atom Speaker Kit with the following config (I have removed wifi, api and ota sections)
```
substitutions:
  name: media-kit-13-a17340
  friendly_name: "M5Stack Atom Speaker Kit"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: m5stack.atom-speaker-kit
    version: "1.0"
  platform: ESP32
  board: m5stack-atom

dashboard_import:
  package_import_url: github://esphome/media-players/m5stack-atom-speaker-kit.yaml@main

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_lrclk_pin: GPIO21
    i2s_dout_pin: GPIO25
    i2s_bclk_pin: GPIO22
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${friendly_name} Button
    on_click:
      - media_player.toggle: media_out

light:
  - platform: fastled_clockless
    name: ${friendly_name}
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
```
The problem seems to be with the TTS playback - I am using PicoTTS and when I try to play simple sentences  (i.e. Someone at the door) parts of the words are often missing  and it is often difficult to understand what is being played. Playing the same thing from PicoTTS via Web Browser is fine - no missing parts.
Strangely enough playing mp3 tracks from local media in HA is fine.
Is this a known problem or do I have my config wrong?
Thanks
